---
# ------------------------------------------------------------------------------------
# -- Docs: https://github.com/imamcs19/edubig-spark-standalone-cluster-and-support-streamlit-port-on-docker --
# -- Additional: Zookeeper, Kafka and port - 8501:8501 for Support Streamlit for JupyterLab
# ------------------------------------------------------------------------------------
version: "3.6"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 54.208.1.149
      KAFKA_ZOOKEEPER_CONNECT: 54.208.1.149:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  jupyterlab:
    image: imamcs/ubig1-jupyterlab:version1.1
    container_name: jupyterlab
    ports:
      - 8888:8888
      - 8501:8501
    volumes:
      - shared-workspace:/opt/workspace
  spark-master:
    image: imamcs/ubig1-spark-master
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
  spark-worker-1:
    image: imamcs/ubig1-spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
  spark-worker-2:
    image: imamcs/ubig1-spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
...
